// Generated automatically by nearley, version 2.19.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }
var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "main", "symbols": ["_", "AS", "_"], "postprocess": ([a, b, c]) => b},
    {"name": "P$macrocall$2", "symbols": ["AS"]},
    {"name": "P$macrocall$1$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "P$macrocall$1$subexpression$1", "symbols": ["P$macrocall$1$subexpression$1$string$1"]},
    {"name": "P$macrocall$1$subexpression$1$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "P$macrocall$1$subexpression$1", "symbols": ["P$macrocall$1$subexpression$1$string$2"]},
    {"name": "P$macrocall$1$subexpression$2$string$1", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "P$macrocall$1$subexpression$2", "symbols": ["P$macrocall$1$subexpression$2$string$1"]},
    {"name": "P$macrocall$1$subexpression$2$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "P$macrocall$1$subexpression$2", "symbols": ["P$macrocall$1$subexpression$2$string$2"]},
    {"name": "P$macrocall$1", "symbols": ["P$macrocall$1$subexpression$1", "_", "P$macrocall$2", "_", "P$macrocall$1$subexpression$2"], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "P", "symbols": ["P$macrocall$1"], "postprocess": ([a]) => `(${a})`},
    {"name": "P", "symbols": ["N"], "postprocess": id},
    {"name": "E$subexpression$1", "symbols": ["E"]},
    {"name": "E$subexpression$1$macrocall$2", "symbols": ["E"]},
    {"name": "E$subexpression$1$macrocall$1", "symbols": [{"literal":"{"}, "_", "E$subexpression$1$macrocall$2", "_", {"literal":"}"}], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "E$subexpression$1", "symbols": ["E$subexpression$1$macrocall$1"], "postprocess": ([a]) => `(${a})`},
    {"name": "E", "symbols": ["P", "_", {"literal":"^"}, "_", "E$subexpression$1"], "postprocess": ([a, b, c, d, e]) => `${a}^${e}`},
    {"name": "E", "symbols": ["P"], "postprocess": id},
    {"name": "MD$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"c"}, {"literal":"d"}, {"literal":"o"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MD$subexpression$1", "symbols": ["MD$subexpression$1$string$1"]},
    {"name": "MD$subexpression$1", "symbols": [{"literal":"*"}]},
    {"name": "MD", "symbols": ["MD", "_", "MD$subexpression$1", "_", "E"], "postprocess": ([a, b, c, d, e]) => `${a}*${e}`},
    {"name": "MD$string$1", "symbols": [{"literal":"\\"}, {"literal":"f"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "MD$macrocall$2", "symbols": ["MD"]},
    {"name": "MD$macrocall$1", "symbols": [{"literal":"{"}, "_", "MD$macrocall$2", "_", {"literal":"}"}], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "MD$macrocall$4", "symbols": ["E"]},
    {"name": "MD$macrocall$3", "symbols": [{"literal":"{"}, "_", "MD$macrocall$4", "_", {"literal":"}"}], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "MD", "symbols": ["MD$string$1", "MD$macrocall$1", "MD$macrocall$3"], "postprocess": ([a, b, c]) => `${a}/${e}`},
    {"name": "MD", "symbols": ["MD", {"literal":"/"}, "E"], "postprocess": ([a, b, c]) => `${a}/${c}`},
    {"name": "MD", "symbols": ["E"], "postprocess": id},
    {"name": "AS", "symbols": ["AS", "_", {"literal":"+"}, "_", "MD"], "postprocess": ([a, b, c, d, e]) => `${a}+${e}`},
    {"name": "AS", "symbols": ["AS", "_", {"literal":"-"}, "_", "MD"], "postprocess": ([a, b, c, d, e]) => `${a}-${e}`},
    {"name": "AS", "symbols": ["MD"], "postprocess": id},
    {"name": "N", "symbols": ["float"], "postprocess": id},
    {"name": "N$string$1", "symbols": [{"literal":"\\"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$2", "symbols": ["P"]},
    {"name": "N$macrocall$1$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$1$subexpression$1", "symbols": ["N$macrocall$1$subexpression$1$string$1"]},
    {"name": "N$macrocall$1$subexpression$1$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$1$subexpression$1", "symbols": ["N$macrocall$1$subexpression$1$string$2"]},
    {"name": "N$macrocall$1$subexpression$2$string$1", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$1$subexpression$2", "symbols": ["N$macrocall$1$subexpression$2$string$1"]},
    {"name": "N$macrocall$1$subexpression$2$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$1$subexpression$2", "symbols": ["N$macrocall$1$subexpression$2$string$2"]},
    {"name": "N$macrocall$1", "symbols": ["N$macrocall$1$subexpression$1", "_", "N$macrocall$2", "_", "N$macrocall$1$subexpression$2"], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N", "symbols": ["N$string$1", "_", "N$macrocall$1"], "postprocess": ([a, b, c]) => `sin(${c})`},
    {"name": "N$string$2", "symbols": [{"literal":"\\"}, {"literal":"c"}, {"literal":"o"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$4", "symbols": ["P"]},
    {"name": "N$macrocall$3$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$3$subexpression$1", "symbols": ["N$macrocall$3$subexpression$1$string$1"]},
    {"name": "N$macrocall$3$subexpression$1$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$3$subexpression$1", "symbols": ["N$macrocall$3$subexpression$1$string$2"]},
    {"name": "N$macrocall$3$subexpression$2$string$1", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$3$subexpression$2", "symbols": ["N$macrocall$3$subexpression$2$string$1"]},
    {"name": "N$macrocall$3$subexpression$2$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$3$subexpression$2", "symbols": ["N$macrocall$3$subexpression$2$string$2"]},
    {"name": "N$macrocall$3", "symbols": ["N$macrocall$3$subexpression$1", "_", "N$macrocall$4", "_", "N$macrocall$3$subexpression$2"], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N", "symbols": ["N$string$2", "_", "N$macrocall$3"], "postprocess": ([a, b, c]) => `cos(${c})`},
    {"name": "N$string$3", "symbols": [{"literal":"\\"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$6", "symbols": ["P"]},
    {"name": "N$macrocall$5$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$5$subexpression$1", "symbols": ["N$macrocall$5$subexpression$1$string$1"]},
    {"name": "N$macrocall$5$subexpression$1$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$5$subexpression$1", "symbols": ["N$macrocall$5$subexpression$1$string$2"]},
    {"name": "N$macrocall$5$subexpression$2$string$1", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$5$subexpression$2", "symbols": ["N$macrocall$5$subexpression$2$string$1"]},
    {"name": "N$macrocall$5$subexpression$2$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$5$subexpression$2", "symbols": ["N$macrocall$5$subexpression$2$string$2"]},
    {"name": "N$macrocall$5", "symbols": ["N$macrocall$5$subexpression$1", "_", "N$macrocall$6", "_", "N$macrocall$5$subexpression$2"], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N", "symbols": ["N$string$3", "_", "N$macrocall$5"], "postprocess": ([a, b, c]) => `tan(${c})`},
    {"name": "N$string$4", "symbols": [{"literal":"\\"}, {"literal":"a"}, {"literal":"r"}, {"literal":"c"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$8", "symbols": ["P"]},
    {"name": "N$macrocall$7$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$7$subexpression$1", "symbols": ["N$macrocall$7$subexpression$1$string$1"]},
    {"name": "N$macrocall$7$subexpression$1$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$7$subexpression$1", "symbols": ["N$macrocall$7$subexpression$1$string$2"]},
    {"name": "N$macrocall$7$subexpression$2$string$1", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$7$subexpression$2", "symbols": ["N$macrocall$7$subexpression$2$string$1"]},
    {"name": "N$macrocall$7$subexpression$2$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$7$subexpression$2", "symbols": ["N$macrocall$7$subexpression$2$string$2"]},
    {"name": "N$macrocall$7", "symbols": ["N$macrocall$7$subexpression$1", "_", "N$macrocall$8", "_", "N$macrocall$7$subexpression$2"], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N", "symbols": ["N$string$4", "_", "N$macrocall$7"], "postprocess": ([a, b, c]) => `arcsin(${c})`},
    {"name": "N$string$5", "symbols": [{"literal":"\\"}, {"literal":"a"}, {"literal":"r"}, {"literal":"c"}, {"literal":"c"}, {"literal":"o"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$10", "symbols": ["P"]},
    {"name": "N$macrocall$9$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$9$subexpression$1", "symbols": ["N$macrocall$9$subexpression$1$string$1"]},
    {"name": "N$macrocall$9$subexpression$1$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$9$subexpression$1", "symbols": ["N$macrocall$9$subexpression$1$string$2"]},
    {"name": "N$macrocall$9$subexpression$2$string$1", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$9$subexpression$2", "symbols": ["N$macrocall$9$subexpression$2$string$1"]},
    {"name": "N$macrocall$9$subexpression$2$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$9$subexpression$2", "symbols": ["N$macrocall$9$subexpression$2$string$2"]},
    {"name": "N$macrocall$9", "symbols": ["N$macrocall$9$subexpression$1", "_", "N$macrocall$10", "_", "N$macrocall$9$subexpression$2"], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N", "symbols": ["N$string$5", "_", "N$macrocall$9"], "postprocess": ([a, b, c]) => `arccos(${c})`},
    {"name": "N$string$6", "symbols": [{"literal":"\\"}, {"literal":"a"}, {"literal":"r"}, {"literal":"c"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$12", "symbols": ["P"]},
    {"name": "N$macrocall$11$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$11$subexpression$1", "symbols": ["N$macrocall$11$subexpression$1$string$1"]},
    {"name": "N$macrocall$11$subexpression$1$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$11$subexpression$1", "symbols": ["N$macrocall$11$subexpression$1$string$2"]},
    {"name": "N$macrocall$11$subexpression$2$string$1", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$11$subexpression$2", "symbols": ["N$macrocall$11$subexpression$2$string$1"]},
    {"name": "N$macrocall$11$subexpression$2$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$11$subexpression$2", "symbols": ["N$macrocall$11$subexpression$2$string$2"]},
    {"name": "N$macrocall$11", "symbols": ["N$macrocall$11$subexpression$1", "_", "N$macrocall$12", "_", "N$macrocall$11$subexpression$2"], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N", "symbols": ["N$string$6", "_", "N$macrocall$11"], "postprocess": ([a, b, c]) => `arctan(${c})`},
    {"name": "N$string$7", "symbols": [{"literal":"\\"}, {"literal":"a"}, {"literal":"s"}, {"literal":"i"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$14", "symbols": ["P"]},
    {"name": "N$macrocall$13$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$13$subexpression$1", "symbols": ["N$macrocall$13$subexpression$1$string$1"]},
    {"name": "N$macrocall$13$subexpression$1$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$13$subexpression$1", "symbols": ["N$macrocall$13$subexpression$1$string$2"]},
    {"name": "N$macrocall$13$subexpression$2$string$1", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$13$subexpression$2", "symbols": ["N$macrocall$13$subexpression$2$string$1"]},
    {"name": "N$macrocall$13$subexpression$2$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$13$subexpression$2", "symbols": ["N$macrocall$13$subexpression$2$string$2"]},
    {"name": "N$macrocall$13", "symbols": ["N$macrocall$13$subexpression$1", "_", "N$macrocall$14", "_", "N$macrocall$13$subexpression$2"], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N", "symbols": ["N$string$7", "_", "N$macrocall$13"], "postprocess": ([a, b, c]) => `asin(${c})`},
    {"name": "N$string$8", "symbols": [{"literal":"\\"}, {"literal":"a"}, {"literal":"c"}, {"literal":"o"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$16", "symbols": ["P"]},
    {"name": "N$macrocall$15$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$15$subexpression$1", "symbols": ["N$macrocall$15$subexpression$1$string$1"]},
    {"name": "N$macrocall$15$subexpression$1$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$15$subexpression$1", "symbols": ["N$macrocall$15$subexpression$1$string$2"]},
    {"name": "N$macrocall$15$subexpression$2$string$1", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$15$subexpression$2", "symbols": ["N$macrocall$15$subexpression$2$string$1"]},
    {"name": "N$macrocall$15$subexpression$2$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$15$subexpression$2", "symbols": ["N$macrocall$15$subexpression$2$string$2"]},
    {"name": "N$macrocall$15", "symbols": ["N$macrocall$15$subexpression$1", "_", "N$macrocall$16", "_", "N$macrocall$15$subexpression$2"], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N", "symbols": ["N$string$8", "_", "N$macrocall$15"], "postprocess": ([a, b, c]) => `acos(${c})`},
    {"name": "N$string$9", "symbols": [{"literal":"\\"}, {"literal":"a"}, {"literal":"t"}, {"literal":"a"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$18", "symbols": ["P"]},
    {"name": "N$macrocall$17$subexpression$1$string$1", "symbols": [{"literal":"\\"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$17$subexpression$1", "symbols": ["N$macrocall$17$subexpression$1$string$1"]},
    {"name": "N$macrocall$17$subexpression$1$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"l"}, {"literal":"e"}, {"literal":"f"}, {"literal":"t"}, {"literal":"("}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$17$subexpression$1", "symbols": ["N$macrocall$17$subexpression$1$string$2"]},
    {"name": "N$macrocall$17$subexpression$2$string$1", "symbols": [{"literal":"\\"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$17$subexpression$2", "symbols": ["N$macrocall$17$subexpression$2$string$1"]},
    {"name": "N$macrocall$17$subexpression$2$string$2", "symbols": [{"literal":"\\"}, {"literal":"m"}, {"literal":"r"}, {"literal":"i"}, {"literal":"g"}, {"literal":"h"}, {"literal":"t"}, {"literal":")"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$17$subexpression$2", "symbols": ["N$macrocall$17$subexpression$2$string$2"]},
    {"name": "N$macrocall$17", "symbols": ["N$macrocall$17$subexpression$1", "_", "N$macrocall$18", "_", "N$macrocall$17$subexpression$2"], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N", "symbols": ["N$string$9", "_", "N$macrocall$17"], "postprocess": ([a, b, c]) => `atan(${c})`},
    {"name": "N$string$10", "symbols": [{"literal":"\\"}, {"literal":"p"}, {"literal":"i"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$10"], "postprocess": ([a]) => "PI"},
    {"name": "N$string$11", "symbols": [{"literal":"\\"}, {"literal":"e"}, {"literal":"x"}, {"literal":"p"}, {"literal":"o"}, {"literal":"n"}, {"literal":"e"}, {"literal":"n"}, {"literal":"t"}, {"literal":"i"}, {"literal":"a"}, {"literal":"l"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$11"], "postprocess": ([a]) => "E"},
    {"name": "N$string$12", "symbols": [{"literal":"\\"}, {"literal":"s"}, {"literal":"q"}, {"literal":"r"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$20", "symbols": ["P"]},
    {"name": "N$macrocall$19", "symbols": [{"literal":"{"}, "_", "N$macrocall$20", "_", {"literal":"}"}], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N", "symbols": ["N$string$12", "_", "N$macrocall$19"], "postprocess": ([a, b, c]) => `sqrt(${c})`},
    {"name": "N$string$13", "symbols": [{"literal":"\\"}, {"literal":"l"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$13", "_", "P"], "postprocess": ([a, b, c]) => `ln(${c})`},
    {"name": "N$string$14", "symbols": [{"literal":"\\"}, {"literal":"i"}, {"literal":"n"}, {"literal":"t"}, {"literal":" "}, {"literal":"^"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$subexpression$1", "symbols": ["P"]},
    {"name": "N$subexpression$1$macrocall$2", "symbols": ["P"]},
    {"name": "N$subexpression$1$macrocall$1", "symbols": [{"literal":"{"}, "_", "N$subexpression$1$macrocall$2", "_", {"literal":"}"}], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N$subexpression$1", "symbols": ["N$subexpression$1$macrocall$1"]},
    {"name": "N$subexpression$2", "symbols": ["P"]},
    {"name": "N$subexpression$2$macrocall$2", "symbols": ["P"]},
    {"name": "N$subexpression$2$macrocall$1", "symbols": [{"literal":"{"}, "_", "N$subexpression$2$macrocall$2", "_", {"literal":"}"}], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N$subexpression$2", "symbols": ["N$subexpression$2$macrocall$1"]},
    {"name": "N", "symbols": ["N$string$14", "N$subexpression$1", {"literal":"_"}, "N$subexpression$2", "P"], "postprocess": ([_1, a, _2, b, c]) => `defint(${c}, x, ${b}, ${a})`},
    {"name": "N$string$15", "symbols": [{"literal":"\\"}, {"literal":"b"}, {"literal":"i"}, {"literal":"n"}, {"literal":"o"}, {"literal":"m"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$macrocall$22", "symbols": ["P"]},
    {"name": "N$macrocall$21", "symbols": [{"literal":"{"}, "_", "N$macrocall$22", "_", {"literal":"}"}], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N$macrocall$24", "symbols": ["P"]},
    {"name": "N$macrocall$23", "symbols": [{"literal":"{"}, "_", "N$macrocall$24", "_", {"literal":"}"}], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N", "symbols": ["N$string$15", "N$macrocall$21", "N$macrocall$23"], "postprocess": ([a, b, c]) => `choose(${b}, ${c})`},
    {"name": "N$string$16", "symbols": [{"literal":"\\"}, {"literal":"s"}, {"literal":"u"}, {"literal":"m"}, {"literal":" "}, {"literal":"^"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$subexpression$3", "symbols": ["P"]},
    {"name": "N$subexpression$3$macrocall$2", "symbols": ["P"]},
    {"name": "N$subexpression$3$macrocall$1", "symbols": [{"literal":"{"}, "_", "N$subexpression$3$macrocall$2", "_", {"literal":"}"}], "postprocess": ([a, b, c, d, e]) => c},
    {"name": "N$subexpression$3", "symbols": ["N$subexpression$3$macrocall$1"]},
    {"name": "N$string$17", "symbols": [{"literal":"_"}, {"literal":"{"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$16", "N$subexpression$3", "N$string$17", "var", {"literal":"="}, "P", {"literal":"}"}, "P"], "postprocess": ([_1, a, _2, b, _3, c, _4, d]) => `sum(${d}, ${b}, ${c}, ${a})`},
    {"name": "N$string$18", "symbols": [{"literal":"\\"}, {"literal":"p"}, {"literal":"r"}, {"literal":"o"}, {"literal":"d"}, {"literal":" "}, {"literal":"^"}, {"literal":"{"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N$string$19", "symbols": [{"literal":"}"}, {"literal":"_"}, {"literal":"{"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "N", "symbols": ["N$string$18", "P", "N$string$19", "var", {"literal":"="}, "P", {"literal":"}"}, "P"], "postprocess": ([_1, a, _2, b, _3, c, _4, d]) => `product(${d}, ${b}, ${c}, ${a})`},
    {"name": "float", "symbols": ["int", {"literal":"."}, "int"], "postprocess": ([a, b, c]) => `${a}${b}${c}`},
    {"name": "float", "symbols": ["int"], "postprocess": ([a]) => a},
    {"name": "float", "symbols": [/[a-z]/], "postprocess": id},
    {"name": "int$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "int$ebnf$1", "symbols": ["int$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "int", "symbols": ["int$ebnf$1"], "postprocess": function(d) {return d[0].join(""); }},
    {"name": "var", "symbols": [/[a-z]/], "postprocess": id},
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", /[\s]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": function(d) {return null; }}
]
  , ParserStart: "main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
